/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminFinanceRouteImport } from './routes/admin/finance'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminExpensesIndexRouteImport } from './routes/admin/expenses/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin/orders/$orderId'
import { Route as ApiAdminPingRouteImport } from './routes/api/admin/ping'
import { Route as ApiTestResetCatalogRouteImport } from './routes/api/test/reset-catalog'
import { Route as ApiAdminCatalogImagesRouteImport } from './routes/api/admin/catalog/images'
import { Route as ApiAdminCatalogProductsRouteImport } from './routes/api/admin/catalog/products'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/admin/finance',
  path: '/admin/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExpensesIndexRoute = AdminExpensesIndexRouteImport.update({
  id: '/admin/expenses/',
  path: '/admin/expenses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/admin/orders/',
  path: '/admin/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/admin/orders/$orderId',
  path: '/admin/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPingRoute = ApiAdminPingRouteImport.update({
  id: '/api/admin/ping',
  path: '/api/admin/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestResetCatalogRoute = ApiTestResetCatalogRouteImport.update({
  id: '/api/test/reset-catalog',
  path: '/api/test/reset-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCatalogImagesRoute = ApiAdminCatalogImagesRouteImport.update({
  id: '/api/admin/catalog/images',
  path: '/api/admin/catalog/images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCatalogProductsRoute = ApiAdminCatalogProductsRouteImport.update({
  id: '/api/admin/catalog/products',
  path: '/api/admin/catalog/products',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/api/admin/ping': typeof ApiAdminPingRoute
  '/api/test/reset-catalog': typeof ApiTestResetCatalogRoute
  '/admin/expenses/': typeof AdminExpensesIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/api/admin/catalog/images': typeof ApiAdminCatalogImagesRoute
  '/api/admin/catalog/products': typeof ApiAdminCatalogProductsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/api/admin/ping': typeof ApiAdminPingRoute
  '/api/test/reset-catalog': typeof ApiTestResetCatalogRoute
  '/admin/expenses': typeof AdminExpensesIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/api/admin/catalog/images': typeof ApiAdminCatalogImagesRoute
  '/api/admin/catalog/products': typeof ApiAdminCatalogProductsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/api/admin/ping': typeof ApiAdminPingRoute
  '/api/test/reset-catalog': typeof ApiTestResetCatalogRoute
  '/admin/expenses/': typeof AdminExpensesIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/api/admin/catalog/images': typeof ApiAdminCatalogImagesRoute
  '/api/admin/catalog/products': typeof ApiAdminCatalogProductsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/finance'
    | '/admin/login'
    | '/admin/'
    | '/admin/orders/$orderId'
    | '/api/admin/ping'
    | '/api/test/reset-catalog'
    | '/admin/expenses/'
    | '/admin/orders/'
    | '/api/admin/catalog/images'
    | '/api/admin/catalog/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/finance'
    | '/admin/login'
    | '/admin'
    | '/admin/orders/$orderId'
    | '/api/admin/ping'
    | '/api/test/reset-catalog'
    | '/admin/expenses'
    | '/admin/orders'
    | '/api/admin/catalog/images'
    | '/api/admin/catalog/products'
  id:
    | '__root__'
    | '/'
    | '/admin/finance'
    | '/admin/login'
    | '/admin/'
    | '/admin/orders/$orderId'
    | '/api/admin/ping'
    | '/api/test/reset-catalog'
    | '/admin/expenses/'
    | '/admin/orders/'
    | '/api/admin/catalog/images'
    | '/api/admin/catalog/products'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
  ApiAdminPingRoute: typeof ApiAdminPingRoute
  ApiTestResetCatalogRoute: typeof ApiTestResetCatalogRoute
  AdminExpensesIndexRoute: typeof AdminExpensesIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  ApiAdminCatalogImagesRoute: typeof ApiAdminCatalogImagesRoute
  ApiAdminCatalogProductsRoute: typeof ApiAdminCatalogProductsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/admin/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/expenses/': {
      id: '/admin/expenses/'
      path: '/admin/expenses'
      fullPath: '/admin/expenses/'
      preLoaderRoute: typeof AdminExpensesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/admin/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/admin/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/ping': {
      id: '/api/admin/ping'
      path: '/api/admin/ping'
      fullPath: '/api/admin/ping'
      preLoaderRoute: typeof ApiAdminPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/reset-catalog': {
      id: '/api/test/reset-catalog'
      path: '/api/test/reset-catalog'
      fullPath: '/api/test/reset-catalog'
      preLoaderRoute: typeof ApiTestResetCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/catalog/images': {
      id: '/api/admin/catalog/images'
      path: '/api/admin/catalog/images'
      fullPath: '/api/admin/catalog/images'
      preLoaderRoute: typeof ApiAdminCatalogImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/catalog/products': {
      id: '/api/admin/catalog/products'
      path: '/api/admin/catalog/products'
      fullPath: '/api/admin/catalog/products'
      preLoaderRoute: typeof ApiAdminCatalogProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
  ApiAdminPingRoute: ApiAdminPingRoute,
  ApiTestResetCatalogRoute: ApiTestResetCatalogRoute,
  AdminExpensesIndexRoute: AdminExpensesIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  ApiAdminCatalogImagesRoute: ApiAdminCatalogImagesRoute,
  ApiAdminCatalogProductsRoute: ApiAdminCatalogProductsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
